services:
    mongodb:
        image: mongo:7
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            # persistent database volume
            - ../app/mongodb_data:/data/db

volumes:
    mongodb_data:
